security:
    # 1️⃣ PROVIDERS – odkud se berou uživatelé
    providers:
        app_user_provider:
            id: App\Security\EmailNeboUsernameProvider

    # 2️⃣ HASHOVÁNÍ HESLA
    password_hashers:
        App\Entity\Uzivatel:
            algorithm: auto

    # 3️⃣ FIREWALLY – jak se uživatel přihlašuje
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: /

    # 4️⃣ OPRÁVNĚNÍ
    access_control:
    # příklad:
    # - { path: ^/admin, roles: ROLE_ADMIN }
